# Generated by Django 3.0.3 on 2020-03-02 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_with_taxes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_date', models.DateField()),
                ('last_update_date', models.DateField()),
                ('state', models.CharField(max_length=2)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.Market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item_purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_with_taxes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_date', models.DateField()),
                ('last_update_date', models.DateField()),
                ('state', models.CharField(max_length=2)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.Purchase')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('brand', models.CharField(max_length=80)),
                ('create_date', models.DateField()),
                ('last_update_date', models.DateField()),
                ('state', models.CharField(max_length=2)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
